name: Develop CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      # GutHub environment claims it's user is root. Doesn't look so.
      # Use of 'sudo' and some tweaks are necessary.
      - name: Prepare environment
        run: sudo ./prepare_debian_environment.sh && sudo chmod o+r "$(readlink -f /boot/vmlinuz)" && sudo chmod 0666 /dev/kvm

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test
